
[services.joblens-be]
type = "web"
name = "joblens-be"
env = "node"
build = "cd JobLens-BE && npm install"
start = "cd JobLens-BE && node server.js"
plan = "free"
[services.joblens-be.env]
NODE_VERSION = "18"

[services.cvextractor]
type = "web"
name = "cvextractor"
env = "python"
build = "cd cvExtractor && pip install -r requirements.txt"
start = "python3 cvExtractor/main.py"
plan = "free"
[services.cvextractor.env]
PYTHON_VERSION = "3.10"
