# Project Configuration
[project]
name = "joblens"

# Node.js Service (JobLens-BE)
[service."joblens-be"]
env = "node"
rootDirectory = "JobLens-BE"
buildCommand = "npm install"
startCommand = "node server.js"
provider = "railway"

# Python Service (cvExtractor)
[service."cvextractor"]
env = "python"
rootDirectory = "cvExtractor"
buildCommand = "pip install -r requirements.txt"
startCommand = "python3 main.py"
provider = "railway"
