services:
  - type: web
    name: joblens-be
    env: node
    buildCommand: 
      apt-get update && apt-get install -y nodejs npm
      cd JobLens-BE && npm install
    startCommand: cd JobLens-BE && node server
    plan: free
  - type: web
    name: cvextractor
    env: python
    buildCommand: cd cvExtractor && pip install -r requirements.txt
    startCommand: python3 cvExtractor/main.py
    plan: free
