services:
  - type: web
    name: joblens-be
    env: node
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      cd JobLens-BE && npm install
    startCommand: cd JobLens-BE && node server
    plan: free
  - type: web
    name: cvextractor
    env: python
    buildCommand: cd cvExtractor && pip install -r requirements.txt
    startCommand: python3 cvExtractor/main.py
    plan: free
